### PR TITLE
Update ReadMe - Broken URL

### PR DESCRIPTION
**Pull request by shashitechno**
Broken / Moved URL

### CODE REVIEW

**Comment by Ph055a** [comment]
You didn't make any changes?

**Comment by shashitechno** [comment]
@Ph055a hey the domain is moved to .in from .com

**Comment by Ph055a** [comment]
I don't see the need for the change it's the same thing.

**Comment by shashitechno** [comment]
Would just help me to build a backlink - if you can please. the current tool works better, has a better uptime record and works with private profiles as well.

**Pull request closed without merging**
